Cargo.toml
Documentation/MacOS.md
Info.plist
src/target/macos/mod.rs
src/target/macos/vmmap.rs
src/target/mod.rs

- Partially address #1
- Implement Target::launch to launch a process in a debug mode (suspended & with ASLR disabled)
- Implement Target::vm_read, a simple wrapper around mach_vm_read

Add initial implementation for macOS target functions

---

Cargo.toml
src/lib.rs
src/symbol/mod.rs
tests/readmem.rs

This works on Mac & Linux. Now we don't have to hardcode variable addresses, yay!

Add a naive implementation for DWARF symbols reader

---

tests/Makefile

Some distributions (like arch) have the flag
```--enable-default-pie``` turned on by default [1].
By having ```-no-pie``` we can be assured that the test executable
addresses will be valid without having to calculate the absolute
ones.
[1] - https://nanxiao.me/en/gccs-enable-enable-default-pie-option-make-you-stuck-at-relocation-r_x86_64_32s-against-error/

Don't produce a dynamically linked PIE executable test 

---

.travis.yml
tests/readmem.rs

Implements #16 . For the time being disables read_memory integration test for macos. When testing on my fork Travis got stuck the first time it run, however after triggering build once again everything passed (I suspect a caching issue on Travis side). After that all tests worked as they should.

Add macos CI

---

Documentation/MacOS.md

The previous instructions did not work in my OSX. 
I had to fill in a full path to the Info.plist file for it to work. 
Not sure if this is the best option, but hey... it works.

Improve OSX build instructions

---

.cirrus.yml
src/target/linux.rs
src/target/mod.rs
src/target/unix.rs
tests/readmem.rs

Hi @nbaksalyar 
- Moved the common code from linux to unix module
- Added `cirrus.yml` to test for BSD (`cargo build` and `cargo test`) on Cirrus CI and it [passes ](https://cirrus-ci.com/task/5952871088783360) for FreeBSD12

Split out code common for all *nix platform

---

src/target/linux.rs
src/target/unix.rs
tests/attach_readmem.rs
tests/testees/.gitignore
tests/testees/longer_hello.rs

Implements attaching to running process on linux. Closes #39. Cannot implement tests because most linux distros have capability to attach to different process disabled.

Attach to process on linux

---

Cargo.toml
examples/repl.rs
src/target/unix.rs

It only supports a subset of the functionality of headcrab, but it is a good example of how to use headcrab.

Add a simple repl example

---

Cargo.toml
src/symbol/mod.rs
src/target/linux.rs
src/target/mod.rs
src/target/unix.rs
tests/readmem.rs
tests/testees/Makefile
tests/testees/hello.rs

Handle pie executables on Linux

---

examples/repl.rs
src/target/linux.rs
src/target/macos/mod.rs
src/target/unix.rs
tests/attach_readmem.rs
tests/readmem.rs
tests/readregs.rs
tests/syscall.rs
tests/test_utils.rs

While there are legitimate use cases where waitpid should not be used, not using it will in most cases lead to race-conditions between stopping execution of the debuggee again and reading/writing state.

More execution commands and use waitpid where sensible

---

src/target/linux.rs
src/target/unix.rs

Closes #48. If debugee was launched by debugger it is killed when debugger exits.

Kill debugee on debugger exit

---

src/lib.rs
src/symbol/mod.rs
src/target/linux.rs

This makes my spellchecker happy, so that I can use it to avoid
adding more typos in the future:-)

Fix spelling in comments and variable names

---

Cargo.toml
examples/repl.rs
src/symbol/mod.rs
src/symbol/source.rs
src/target/linux.rs
src/target/unix.rs
tests/disassemble.rs
tests/fixed_breakpoint.rs
tests/source.rs
tests/testees/.gitignore
tests/testees/Makefile
tests/testees/known_asm.S

Blocked on https://github.com/gimli-rs/addr2line/issues/187 to get addr2line working files compiled from assembly. Otherwise the line info test fails.

Add disassembler and line info parsing

---

examples/repl.rs
src/symbol/mod.rs
src/symbol/sym.rs
tests/unwind_stack.rs

I'm not sure if this is the approach you wanted, but I think this should work.
Resolves #71

Symbol demangling

---

src/symbol/mod.rs

`entry.address_range.1` represents a size, not an address. This caused problems in #73.

Correctly handle entry.address_range

---

src/target/linux.rs

Fixes #80  
Can handle the failure to obtain the name of a thread. This might
happen for different reasons (e.g., maybe the thread is not there
anymore). I'm keeping the error as the name to show in the assertions
failures.

Make threads test more robust

---

examples/repl.rs

Fixes #89 
Adds a `help|h` command

Add help to repl

---

Cargo.toml
examples/repl.rs
repl_tools/Cargo.toml
repl_tools/src/lib.rs
src/target/linux.rs
tests/test_utils.rs

Add syntax highlighting and completion to repl

---

Cargo.toml
examples/inject_dylib.clif
examples/inject_hello_world.clif
examples/repl.rs
headcrab_inject/Cargo.toml
headcrab_inject/src/lib.rs
headcrab_inject/src/memory.rs
headcrab_inject/tests/inject_abort.rs
headcrab_inject/tests/test_utils.rs
headcrab_inject/tests/testees
hello_dylib.rs
src/target/linux.rs

```
Starting program: tests/testees/hello
Stopped(Pid(10787), SIGTRAP)
> _patch_breakpoint_function
> cont
Stopped(Pid(10787), SIGTRAP)
> inject examples/inject_hello_world.clif
run function: 0x00007ffff7fca030 stack: 0x00007ffff7fc8ff8
Hello World from injected code!
Stopped(Pid(10787), SIGTRAP) at 0x00007ffff7fca001
> injectlib libhello_dylib.so
run function: 0x00007ffff7fc7008 stack: 0x00007ffff7fc5ff8
orig rip: 0000555555559295
Hello World from dylib!
Stopped(Pid(10787), SIGTRAP) at 0x00007ffff7fc7001
> cont
Hello, world!
42
Exited(Pid(10787), 0)
Exit
```
I will leave the following improvements [I mentioned on zulip](https://headcrab.zulipchat.com/#narrow/stream/248039-general/topic/injecting.20code.20into.20process/near/209233083) to a followup:
* allow reusing code across multiple …

Inject code into the debugged process

---

examples/repl.rs
headcrab_inject/src/lib.rs
headcrab_inject/src/memory.rs
headcrab_inject/src/module.rs
headcrab_inject/tests/inject_abort.rs

This makes it easier to add a `cranelift_module::Module` implementation to inject rust code using cg_clif in the future.

Refactor headcrab_inject

---

examples/repl.rs

The `x` causes all numbers to be formatted as hex. The `#` causes both an `0x` prefix to be added to all hex numbers and the register struct to span multiple lines. The `016` causes all hex numbers to be zero padded to 16 chars.
Found this trick at http://dtrace.org/blogs/bmc/2020/10/11/rust-after-the-honeymoon/

Use {:#016x?} for register printing

---

Cargo.toml
examples/gui.rs
examples/repl.rs
src/target.rs
src/target/linux.rs
src/target/macos.rs
src/target/registers.rs
src/target/thread.rs
tests/disassemble.rs
tests/fixed_breakpoint.rs
tests/read_locals.rs
tests/readmem.rs
tests/readregs.rs
tests/runtime_breakpoint.rs
tests/source.rs
tests/test_utils.rs
tests/unwind_stack.rs

Add API to read & write registers for Linux

---

Cargo.toml
src/symbol.rs
src/target/linux.rs
src/target/linux/software_breakpoint.rs
src/target/linux/writemem.rs

- Update `gimli` and `addr2line` deps.
- Fix race in the `writemem` test: it incorrectly called both `PTRACE_TRACEME` in the child process and `PTRACE_ATTACH` in the parent process while only `PTRACE_TRACEME` is required. This could have resulted in a race condition.
- Expose `LinuxTarget::new` as public API for the cases when we know that the tracee expects to be attached to (i.e. it called `PTRACE_TRACEME`).

Fix race condition in the writemem test

---

headcrab_inject/Cargo.toml
headcrab_inject/src/lib.rs
headcrab_inject/src/module.rs
headcrab_inject/tests/inject_abort.rs

* Fix the `inject_abort` test.
* Simplify injection code (we don't need to use sinks to obtain relocs info anymore).

Update Cranelift dependency in headcrab_inject
